IBM/design-system-website

src/content/style/grid/code.md

* Added in documentation from @chrisdhanaraj about Flexbox
Resolves some of [#38 ](https://github.com/carbon-design-system/carbon-components/issues/38)

Flexbox docs to Grid page

---

src/content/components/data-vis/circle-gauge/style.md
src/content/components/data-vis/overview/style.md
src/internal/OverviewPage/OverviewPage.js

* Fixed link on Overview page that doesn't link out to Data Vis 
Ref #15

Fixed broken Data Vis link

---

src/assets/fonts/font-face.scss
src/content/add-ons/overview.md
src/data/add-ons/inline-left-nav.js
src/internal/CodePage/CodePage.js
src/internal/SideNav/SideNav.js
src/pages/add-ons/ComponentPage.js
src/pages/add-ons/OverviewPage.js
src/pages/guidelines/Guidelines.js

fixes to v8 pages

---

src/internal/OverviewPage/OverviewPage.js
src/internal/OverviewPage/images/Tile.svg
src/pages/data-vis/DataVis.js
src/routes.js

- added tile and text input to the overview page
- changed data vis tab from 'usage' to 'general'

updates to overview page

---

src/content/getting-started/service-providers/service-providers.md

People were asking questions about how to submit a service icon, so I updated the guidelines to include this.

Internal::Updated Service Provider content 

---

src/internal/IconCard/IconCard.scss
src/internal/MarkdownPage/markdown-page.scss
src/internal/Page/page.scss
src/internal/PageHeader/page-header.scss
src/internal/SideNav/sidenav.scss
src/pages/resources/resources.scss

Ref https://github.ibm.com/Bluemix/carbon-issues/issues/213

Updated Plex on the website

---

src/content/components/data-vis/pie-chart/code.md
src/content/components/data-vis/scatterplot/code.md
src/data/site-nav-structure.json
src/internal/SideNavItem/SideNavItem.js

**Added:**
- Scatterplot
- Pie chart
**Fixed:**
- Side nav height

[WIP] Data vis content updates and side nav fix

---

package.json
src/content/components/data-table/code.md
src/data/component-status.json
src/data/components/data-table.js
src/internal/CodePage/CodePage.js
src/internal/CodePage/code-page.scss
src/internal/LiveComponent/LiveComponent.js
src/internal/PageFooter/PageFooter.js
src/pages/ComponentStatus.js
src/pages/components/ComponentPage.js
yarn.lock

- New tables
- Contributing guidelines

Website Deployment

---

src/content/components/accordion/style.md
src/content/style/colors/usage.md
src/content/themes/themes.md
src/data/colors.json
src/data/component-status.json

* Removed Add-ons from Component Status page
* Removed `nav` colors from colors page (resolves [#359](https://github.ibm.com/Bluemix/carbon-issues/issues/359) ) 
* Updated Themes page to remove "Carbon Theme"

Removed nav colors and updated component status

---

src/content/getting-started/FAQ/FAQ.md

* Updated FAQ page to include our Featured section and articles
@marijohannessen or @tw15egan , could you add in the tiles to the *Featured* and *Articles* section?

FAQ page updates

---

src/content/getting-started/FAQ/FAQ.md

Addressing issue [#325](https://github.com/carbon-design-system/carbon-components/issues/325)

Updated content on the FAQ page

---

package.json
src/app/components/custom/ArticleTiles/article-tiles.scss
src/app/components/custom/TypeStylesTable/type-styles-table.scss
src/app/components/internal/MarkdownPage/markdown-page.scss
src/app/components/internal/PageFooter/page-footer.scss
src/app/components/internal/PageHeader/page-header.scss
src/app/components/internal/SideNav/_main-nav.scss
src/app/components/internal/SideNav/sidenav.scss
src/app/components/internal/SideNavItem/SideNavItem.js
src/app/components/internal/SideNavToggle/toggle-btn.scss
src/app/pages/overview/Overview.js
src/app/pages/overview/overview.scss
src/data/components/data-table.js
yarn.lock

Resolves https://github.ibm.com/Bluemix/carbon-issues/issues/372

Bug fixes post V8

---

src/app/components/internal/MarkdownPage/markdown-page.scss

Resolves https://github.ibm.com/Bluemix/carbon-issues/issues/372

Fixed structured list to scroll on mobile screens

---

config/paths.js
config/webpack.config.dev.js
config/webpack.config.prod.js
package.json
public/index.hbs
src/app/components/internal/CodePage/CodePage.js
src/app/components/internal/LiveComponent/LiveComponent.js
src/carbon-components.js
src/polyfills/custom-event.js
src/polyfills/element-closest.js
src/polyfills/element-matches.js
src/polyfills/index.js
src/polyfills/toggle-class.js

Refs carbon-design-system/carbon-components#433.

fix(polyfill): support IE11

---

src/app/scss/global/_typography.scss

Porting: https://github.com/carbon-design-system/carbon-components/pull/427

Fix Plex font loading order

---

src/content/components/data-vis/overview/general.md
src/content/getting-started/service-providers/service-providers.md

fixed grammar errors and deleted redundant content

edits to overview tab

---

src/content/style/grid/design.md

Closes https://github.com/carbon-design-system/design-system-website/issues/93

Fixed busted link

---

src/app/components/internal/PageFooter/PageFooter.js
src/app/pages/component-status/ComponentStatus.js

Updated dates in copyright text and footer

---

src/content/components/slider/style.md

Added docs about slider

---

src/app/components/internal/CodePage/CodePage.js
src/app/pages/add-ons/ComponentPage.js

Removed Codepen links on add-on component pages

---

src/app/pages/getting-started/service-providers.scss

Style updates to Service Providers page

---

src/content/getting-started/service-providers/service-icon.md

Updated the process for submitting icons as per Connors instructions.

Updated icon approval and submission section

---

src/app/components/internal/CodePage/CodePage.js

Fixed JS for the add-ons components

---

src/content/getting-started/developers/developers.md

We have received many questions in that area, and this change attempts to alleviate the confusions people may have had between our `.create()`/`.init()` APIs.

docs(JavaScript): improved documentation on component lifecycle

---

package.json
public/index.hbs
src/app/components/custom/LayerTypes/layer-types.scss
src/app/components/custom/MotionExample/MotionExample.js
src/app/components/custom/MotionExample/motion-example.scss
src/app/components/internal/CodeExample/CodeExample.js
src/app/components/internal/Glossary/Glossary.js
src/app/components/internal/IconCard/IconCard.js
src/app/components/internal/IconCard/IconCard.scss
src/app/components/internal/OverviewPage/OverviewPage.js
src/app/components/internal/Page/Page.js
src/app/components/internal/PageTabs/PageTabs.js
src/app/components/internal/SideNav/SideNav.js
src/app/pages/component-status/ComponentStatus.js
src/app/pages/guidelines/guidelines.scss
src/app/pages/overview/Overview.js
yarn.lock

Was able to get rid of most of the a11y violations mentioned in this issue #152

Fixed some a11y violations

---

package.json
src/app/components/internal/CodePage/CodePage.js
src/app/components/internal/ComponentReactExample/ComponentReactExample.js
src/app/components/internal/ComponentReactExample/component-example.scss
src/app/components/internal/ComponentReactExample/component-overrides.scss
src/app/components/internal/ComponentReactExample/index.js
src/content/components/dropdown/code.md
src/data/components/dropdown.js
yarn.lock

Added
- MultiSelect
- Filterable MultiSelect
- Inline MultiSelect
🎉

Added React dropdown components

---

src/content/whats-new/whats-new.md

Updated the whats new page for the latest carbon release.

What's new page updates

---

package.json
src/app/components/internal/PageFooter/PageFooter.js
src/app/pages/overview/Overview.js
src/content/components/modal/style.md
yarn.lock

Deployment April 26

---

src/content/whats-new/whats-new.md

The content for this PR was review in #197

added in what's new section

---

src/app/components/internal/PageFooter/page-footer.scss
src/app/components/internal/SideNav/_main-nav.scss
src/app/components/internal/SideNav/sidenav.scss

- added an underline to focus state for left-nav items and logo #167 
- added outline to links in footer #168

Left nav a11y fixes

---

src/data/component-status.json

Ref https://github.ibm.com/carbon/issues/issues/707#issuecomment-6351469

Updated component status page

---

src/app/pages/style/Iconography.js

Note: depends on an updated release of carbon-icons with the new formatting changes

fix(icons): add print logic for svgString

---

src/content/components/code-snippet/usage.md
src/content/whats-new/whats-new.md

- Fixed list on What's New page
- Fixed broken link on Code Snippet usage page
Closes https://github.com/carbon-design-system/design-system-website/issues/248

Release hot fixes

---

package-lock.json
src/content/components/code-snippet/style.md
src/content/components/tooltip/style.md

- Removed HEX code all caps from Code Snippet > Style
- Removed all caps in table headers on Tooltip page
- Fixed Tooltip image sizing
😘

Fixed content and image bugs

---

src/content/components/tooltip/usage.md

Cut/paste errors on Tooltip Usage page #270

---

src/app/pages/overview/Overview.js

Small improvements to link text on Overview page #274

---

src/app/pages/style/Iconography.js
src/content/getting-started/developers/vanilla.md

- Removed all old Carbon glyph icons from the iconography page
- Fixed broken link, closes https://github.com/carbon-design-system/design-system-website/issues/278

fix(global): misc fixes such as icons, broken link

---

package.json
src/app/components/internal/CodePage/CodePage.js
src/app/components/internal/ComponentExample/ComponentExample.js
yarn.lock

@asudoh I had to revert your changes cause apparently it broke the components pages. I didn't catch this when I reviewed it. Can you make a new PR with the changes and then make sure all the component pages work?

fix(code-page): fix broken components

---

src/content/getting-started/FAQ/FAQ.md

- Added the v8 link to the FAQ page

Add V8 link

---

src/app/components/custom/CursorTable/CursorTable.js
src/app/components/custom/CursorTable/cursor-table.scss
src/app/components/custom/CursorTable/index.js
src/app/components/internal/Page/Page.js
src/app/components/internal/SideNav/sidenav.scss
src/app/scss/main.scss
src/content/utilities/system-defaults/system-defaults.md

Created a custom component `CursorTable` in order to style the cursor table on the new Utilities page.

Fixed table on cursor page

---

package.json
src/app/components/internal/SideNav/sidenav.scss
yarn.lock

fix sidenav button hover

---

src/content/add-ons/overview.md

first draft of updated contribution docs for add-ons
https://github.ibm.com/carbon/issues/issues/482

update add-on docs

---

src/content/guidelines/accessibility/color.md
src/content/style/color/usage.md

broken links fix

---

src/content/getting-started/developers/react.md

add storybook link

---

config/webpack.config.dev.js
config/webpack.config.prod.js
package.json
src/app/scss/global/_import-once.scss
src/app/scss/main.scss
yarn.lock

> You now need to add carbon-demo-override in addition to carbon-x to get the Carbon X style.

Scoped styles
