IBM/design-system-website

src/data/site-nav-structure.json

I don't think there should be an apostrophe in Add-Ons.

Removed the apostrophe in Add-On's to be Add-Ons

---

src/content/components/data-table/code.md
src/data/components/data-table.js

Only show v2 data tables, add link to older docs

fix(data-table): remove references to v1 tables, link to old docs

---

src/content/components/tag/style.md

Tag colors were removed from the Style tab of the Tag component (since these aren't in our color palette and library).

Removed colors from Tag page

---

src/app/components/internal/MarkdownPage/markdown-page.scss
src/assets/syntax/syntax.css

Fixed a font-family declaration that most likely is causing IBM plex mono to not show on mobile.

updated plex mono on mobile

---

src/content/getting-started/service-providers/general.md

* Fixed broken link for SP guidelines (internal)
I noticed that the "do's and don'ts" aren't styled properly. The whole section and images under Icon guidelines should be styled like this. 
I'm okay to push this to deploy next week since we're limited on time. Just let me know what you think @marijohannessen !

Fixed broken link in SP guidelines

---

package.json
src/content/components/toggle/code.md
src/data/components/toggle.js
yarn.lock

Need to update `carbon-components` once a new release is released before deploying the website because of duplicate ID issue.

Added small toggle component

---

src/app/pages/overview/Overview.js
src/polyfills/index.js

Fixes #196.
This changes does the following:
* Add required polyfills for `carbon-components-react`
* Eliminate `NodeList.forEach()` call as it's not supported by IE11

fix(misc): ie11 fixes

---

src/app/components/internal/MarkdownPage/markdown-page.scss
src/app/components/internal/Page/page-overwrites.scss
src/app/pages/utilities/Utilities.js
src/content/utilities/disabled-states/disabled-states.md
src/content/utilities/filtering/filtering.md
src/content/utilities/loading/loading.md
src/content/utilities/overflow-content/overflow-content.md

Fixes to Utilities section

---

src/app/components/internal/SideNav/SideNav.js
src/app/components/internal/SideNav/_sub-nav.scss
src/app/components/internal/SideNavItem/SideNavItem.js

By letting React handle `tabIndex` property instead of doing so via DOM.
Also:
* Fixes the focus style of sub-expando
* Supports opening/closing sub-expando with keyboard
* Addresses: #208
Review will be easier by clicking on “Diff settings” and checking off "Hide whitespace changes”.

Fix JS error navigating to sub-expando with keyboard

---

src/routes.js

Added redirect from `getting-started/service-providers` to `your-product-on-ibm-cloud/service-providers`

Fixed redirect from old route

---

.gitignore
package.json
scripts/frontmatter.js
scripts/templates.js
src/app/components/internal/CodePage/CodePage.js
src/app/components/internal/LiveComponent/LiveComponent.js
src/content/components/button/code.md
src/content/components/code-snippet/code.md
src/content/components/data-table/code.md
src/content/components/date-picker/code.md
src/content/components/dropdown/code.md
src/content/components/modal/code.md
src/content/components/search/code.md
src/content/components/select/code.md
src/content/components/text-input/code.md
yarn.lock

Supersedes #204. Here are the list of the changes:
* Change from #204 - Changes the HTML file references from ones in `node_modules/carbon-components/src` to ones in `node_modules/carbon-components/html` (built version)
* A way to use component variant labels defined in Handlebars template configuration in `carbon-components`. It's applied *only* if no corresponding information is found in `code.md`
* `code.md` changes to reflect the latest in `carbon-components`' `v9` branch
**Important note**: `package.json` reference to `carbon-components` is to local filesystem for now, assuming `design-system-website` is located as a sibling to `carbon-components`. It should be changed to `9.0.0` release of `carbon-components` before we deploy our V9 release.
Related changes in Carbon:
* …

Carbon V9 merge

---

src/app/components/internal/SideNav/SideNav.js

- Fixes skip link by adding `href="#maincontent"`
- also removed `role="button"` because a skip link is a "link"
(note: don't need explicit `role="link"` because the default role for anchor elements is "link")
- also removed `tabindex="0"` because an anchor with an href is in the tab order by default

Skip link doesn't work #263

---

src/app/components/internal/PageFooter/PageFooter.js

- Uses `aria-label` instead of `alt` on anchor links in the footer
- One of the links (the component version link) had alt text that was quite different from the visual text. This type of thing is a problem for speech recognition systems users, who would expect to say, for example:
> "Click 9.0.0 link"
to activate the link, but since aria-label and aria-labelledby override the link's label, and since the original alt text was "Carbon Components GitHub repo", the voice command would not know which link to click.
To fix this particular link, I decided to use a 2-part label (the aria-labelledby points to 2 ids) to concatenate the string "Component version" with the version string (9.0.0) which gives: "Component version 9.0.0". So the voice command:
> "Click 9.0.0 link"
will actually find the …

'a' elements do not support 'alt' #267

---

src/app/pages/style/Iconography.js

Updates the iconography page to exclude deprecated icons. Also separates out service icons into their own section.
cc @tay-aitken

fix(Iconography): update page to render service icons and exclude glyphs

---

src/app/pages/getting-started/Developers.js
src/content/getting-started/developers/other.md
src/content/getting-started/developers/vanilla.md

https://github.ibm.com/carbon/issues/issues/804
Adds a new Getting Started tab for developers using a framework other than vanilla/react. 
Wasn't sure if we wanted to link out to any of the unofficial angular or vue frameworks, although I think they are internal anyway?

Add new getting started for other frameworks page

---

src/app/App.js
src/index.js

This change adds an attribute to the top-level node in `<App>`, indicating that floating menus should be put there. Also puts a hidden `<input>` next to `<App>` to trap keyboard focus.
Fixes carbon-design-system/carbon-components#910.

Define floating menu target

---

src/content/getting-started/developers/vanilla.md

Many developers who are used to JavaScript frameworks seems to have an false impression that our vanilla library takes care of stamping out the markup.
This change is for making it more clear that application should take care of stamping out the markup.

Add a document for HTML snippet usage

---

src/content/style/grid/code.md

This is the documentation for the feature introduced in the PR https://github.com/IBM/carbon-components/pull/981 , as requested by @alisonjoseph .
This adds a section defining the usage of the `bx--offset` classes.

docs(grid): document the offset usage

---

src/content/guidelines/content/glossary.md

The text "Use instead of Modify unless you are modifying a table." doesn't apply. We don't include "modify" in the list of approved action labels.

Updated subtext for "edit"

---

src/content/utilities/loading/loading.md

- Update the loading utility to capture the recommended loading pattern as discussed with @tay-aitken (😢) and @aagonzales 
-Removes any reference from the overlay loading spinner in the loading guidelines. Also redefines the Small Loading component with the Inline Loading Component as a more expansive version.
I'm not a copywriter so please let me know if you have any other changes.

feat(loading): update loading utility to remove loading overlay component

---

src/app/components/internal/ComponentExample/ComponentExample.js

i removed the all the consts/etc for rendering the 'view on codepen' link in component examples

chore(codepen): remove view in codepen link from component examples
